/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.*;
import Interface.Airliner.SearchJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Apurva
 */
public class optionsAirlinerJPanel extends javax.swing.JPanel {
private JPanel UserProcessContainer;
private AirlinerDirectory airlinerDirect;
    /**
     * Creates new form optionsAirlinerJPanel
     */


    public optionsAirlinerJPanel(JPanel UserProcessContainer, AirlinerDirectory airlinerDirect) {
        initComponents();
         this.airlinerDirect = airlinerDirect ;
         this.UserProcessContainer = UserProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAirlinerjButton = new javax.swing.JButton();
        updateviewjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        createAirlinerjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        createAirlinerjButton.setText("Create an Airliner");
        createAirlinerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirlinerjButtonActionPerformed(evt);
            }
        });

        updateviewjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updateviewjButton.setText("Update/View Airliner");
        updateviewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateviewjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Travel Agency Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(createAirlinerjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateviewjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(createAirlinerjButton)
                .addGap(65, 65, 65)
                .addComponent(updateviewjButton)
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAirlinerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirlinerjButtonActionPerformed
        // TODO add your handling code here:
       createAirlinerJPanel createJPanel = new createAirlinerJPanel(UserProcessContainer, airlinerDirect);
       UserProcessContainer.add("createAirlinerJPanel", createJPanel);
       CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
       layout.next(UserProcessContainer);
    }//GEN-LAST:event_createAirlinerjButtonActionPerformed

    private void updateviewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateviewjButtonActionPerformed
        // TODO add your handling code here:
       updateviewJPanel createJPanel = new updateviewJPanel(UserProcessContainer, airlinerDirect);
       UserProcessContainer.add("updateviewJPanel", createJPanel);
       CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
       layout.next(UserProcessContainer);
    }//GEN-LAST:event_updateviewjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAirlinerjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton updateviewjButton;
    // End of variables declaration//GEN-END:variables
}
