/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliner;

import Business.Airliner;
import Business.Flight;
import Business.FlightSchedule;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Apurva
 */
public class CreateAirlinerSchedule extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirlinerSchedule
     */
    private JPanel UserProcessContainer;
    private FlightSchedule flightSch;
  //  private Flight f;

    public CreateAirlinerSchedule(JPanel UserProcessContainer,FlightSchedule flightSch ) {
        initComponents();
        this.flightSch = flightSch;
        this.UserProcessContainer = UserProcessContainer;
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FromTxtField = new javax.swing.JTextField();
        ToTxtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PricetxtField = new javax.swing.JTextField();
        TimetxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(NameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 66, 150, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 63, 116, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Source:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 115, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Destination:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 162, -1, -1));
        add(FromTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 118, 150, -1));
        add(ToTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 165, 150, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 343, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Price:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 209, 116, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Timeslot:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 30));
        add(PricetxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 212, 150, -1));
        add(TimetxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 259, 150, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Enter Flight Details:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 16, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("(Morning/Evening/Night)");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = NameTxtField.getText();
        String from = FromTxtField.getText();
        String to = ToTxtField.getText();
        int price = Integer.parseInt(PricetxtField.getText());
        String time = TimetxtField.getText();
        
       
        Flight fligt= flightSch.addflightschedule();
        
        fligt.setFlightName(name);
        fligt.setDepart(from);
        fligt.setArrival(to);
        fligt.setPrice(price);
        fligt.setTimestamp(time);
        JOptionPane.showMessageDialog(null,"Saved");


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FromTxtField;
    private javax.swing.JTextField NameTxtField;
    private javax.swing.JTextField PricetxtField;
    private javax.swing.JTextField TimetxtField;
    private javax.swing.JTextField ToTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
