/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliner;

import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Apurva
 */
public class optionsTAJPanel extends javax.swing.JPanel {

    private JPanel UserProcessContainer;
    private FlightSchedule flightSch;
  //  private Airliner a;
    private Flight f;

    /**
     * Creates new form optionsTAJPanel
     */
    public optionsTAJPanel(JPanel UserProcessContainer, FlightSchedule flightSch,Flight f) {
        initComponents();
        this.flightSch = flightSch;
        this.UserProcessContainer = UserProcessContainer;
        this.f = f; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browseFlightnumberjButton = new javax.swing.JButton();
        searchFlightnumberjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        browseFlightnumberjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        browseFlightnumberjButton.setText("Browse all flights List");
        browseFlightnumberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFlightnumberjButtonActionPerformed(evt);
            }
        });

        searchFlightnumberjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        searchFlightnumberjButton.setText("Search Flight");
        searchFlightnumberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightnumberjButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Enter Flight Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Airliner Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchFlightnumberjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(browseFlightnumberjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(searchFlightnumberjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(browseFlightnumberjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFlightnumberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightnumberjButtonActionPerformed
        // TODO add your handling code here:
        SearchJPanel createJPanel = new SearchJPanel(UserProcessContainer, flightSch);
        UserProcessContainer.add("SearchJPanel", createJPanel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_searchFlightnumberjButtonActionPerformed

    private void browseFlightnumberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFlightnumberjButtonActionPerformed
        // TODO add your handling code here:
        listTAJPanel viewJPanel = new listTAJPanel(UserProcessContainer, flightSch);
        UserProcessContainer.add("listTAJPanel", viewJPanel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);

    }//GEN-LAST:event_browseFlightnumberjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateAirlinerSchedule createJPanel = new CreateAirlinerSchedule(UserProcessContainer, flightSch);
        UserProcessContainer.add("CreateAirlinerSchedule", createJPanel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseFlightnumberjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchFlightnumberjButton;
    // End of variables declaration//GEN-END:variables
}
