/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliner;

import Business.*;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Apurva
 */
public class SearchJPanel extends javax.swing.JPanel {

    private JPanel UserProcessContainer;
    private FlightSchedule flightSch;
    private String anumber;

    /**
     * Creates new form SearchJPanel
     */
    public SearchJPanel(JPanel UserProcessContainer, FlightSchedule flightSch) {
        initComponents();
        this.flightSch = flightSch;
        this.UserProcessContainer = UserProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchflightNumberjTextField = new javax.swing.JTextField();
        searchByflightnumberjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightbynumberjTable = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Search by Airliner Name:");

        searchByflightnumberjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        searchByflightnumberjButton.setText("Search");
        searchByflightnumberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByflightnumberjButtonActionPerformed(evt);
            }
        });

        flightbynumberjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name", "Source", "Departure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(flightbynumberjTable);
        if (flightbynumberjTable.getColumnModel().getColumnCount() > 0) {
            flightbynumberjTable.getColumnModel().getColumn(0).setResizable(false);
            flightbynumberjTable.getColumnModel().getColumn(1).setResizable(false);
            flightbynumberjTable.getColumnModel().getColumn(2).setResizable(false);
        }

        backjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchflightNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchByflightnumberjButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchflightNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByflightnumberjButton))
                .addGap(114, 114, 114)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(backjButton)
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        UserProcessContainer.remove(this);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.previous(UserProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void searchByflightnumberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByflightnumberjButtonActionPerformed

        int i = 0, k = 0;
        System.out.println("search");
        try {
            System.out.println("in try");
            anumber = searchflightNumberjTextField.getText();
            System.out.println(anumber);
        } catch (Exception e) {
            System.out.println("Some Exception");
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Plese enter correct values");
            i = 1;
        }
        //System.out.println(ad.getAirplaneDirectory().size());      

        for (Flight f : flightSch.getFlightCollection()) {
            System.out.println("In for");
            Object data[] = new Object[4];

            //String x = ap.getFlightNumber();
            if (anumber.equalsIgnoreCase(f.getFlightName())) {
                k = 1;
                data[0] = f.getFlightName();
                data[1] = f.getArrival();
                data[2] = f.getDepart();
                // data[3] = ap.getAirportName();
                DefaultTableModel dm = (DefaultTableModel) flightbynumberjTable.getModel();
                //dm.setRowCount(0);
                dm.addRow(data);
            }
        }
        if (k == 0) {
            UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 24));
            JOptionPane.showMessageDialog(null, "Invalid Input. Plese enter correct values");
        }
//        try {
//            Airliner airliner = airlinerDirectory.searchAccount(searchflightNumberjTextField.getText());
//
//            if (airliner == null) {
//                JOptionPane.showMessageDialog(null, "Product does not exist");
//            }
//            else{
//                ViewPanel panel = new ViewPanel(rightPanel, Result, prodDir);
//                rightPanel.add("ViewPanel", panel);
//                CardLayout layout = (CardLayout) rightPanel.getLayout();
//                layout.next(rightPanel);
//            }
//        } catch (Exception e) {
//
//            JOptionPane.showMessageDialog(null, "Product Name entered does not exist", "Warning", JOptionPane.WARNING_MESSAGE);
//
//        }
//            }
//        }
    }//GEN-LAST:event_searchByflightnumberjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JTable flightbynumberjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchByflightnumberjButton;
    private javax.swing.JTextField searchflightNumberjTextField;
    // End of variables declaration//GEN-END:variables
}
