/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.*;
import Interface.manageCust.optioncustJPanel;
import Interface.Airliner.optionsTAJPanel;
import Interface.TravelAgency.optionsAirlinerJPanel;
import java.awt.CardLayout;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.GroupLayout.Alignment.values;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Apurva
 */
public class MainJFrame extends javax.swing.JFrame {

    private AirlinerDirectory airlinerDirectory;
    private FlightSchedule flightSch;
    private SeatDirectory sd;
    private Flight f;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.airlinerDirectory = new AirlinerDirectory();
        this.flightSch = new FlightSchedule();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        manageAirlinerjButton = new javax.swing.JButton();
        ManageTravelBtn = new javax.swing.JButton();
        manageCustjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        UserProcessContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAirlinerjButton.setText("Manage Airliners");
        manageAirlinerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlinerjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageAirlinerjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 180, -1));

        ManageTravelBtn.setText("Manage Travel Agency");
        ManageTravelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageTravelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ManageTravelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, -1));

        manageCustjButton.setText("Manage Customer");
        manageCustjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(manageCustjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 170));

        jSplitPane1.setLeftComponent(jPanel1);

        UserProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(51, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 431, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        jLabel1.setText("Flight Reservation System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 189, 553, 55));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 413, -1, -1));

        UserProcessContainer.add(jPanel2, "card2");

        jSplitPane1.setRightComponent(UserProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageAirlinerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlinerjButtonActionPerformed
        // TODO add your handling code here:
        optionsTAJPanel panel = new optionsTAJPanel(UserProcessContainer, flightSch, f);
        UserProcessContainer.add("optionsTAJPanel", panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_manageAirlinerjButtonActionPerformed

    private void ManageTravelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageTravelBtnActionPerformed
        // TODO add your handling code here:
        optionsAirlinerJPanel panel = new optionsAirlinerJPanel(UserProcessContainer, airlinerDirectory);
        UserProcessContainer.add("optionsAirlinerJPanel", panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_ManageTravelBtnActionPerformed

    private void manageCustjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustjButtonActionPerformed
        // TODO add your handling code here:
        optioncustJPanel panel = new optioncustJPanel(UserProcessContainer, flightSch);
        UserProcessContainer.add("optionscustJPanel", panel);
        CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
        layout.next(UserProcessContainer);
    }//GEN-LAST:event_manageCustjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageTravelBtn;
    private javax.swing.JPanel UserProcessContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageAirlinerjButton;
    private javax.swing.JButton manageCustjButton;
    // End of variables declaration//GEN-END:variables
}
