/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.manageCust;

import Business.CustomerDirectory;
import Business.FlightSchedule;
import Business.SeatDirectory;
import Business.Seats;
import Interface.Airliner.SearchJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Apurva
 */
public class optioncustJPanel extends javax.swing.JPanel {
private JPanel UserProcessContainer;
private FlightSchedule flightSch;
private SeatDirectory st;
private CustomerDirectory cd;
    /**
     * Creates new form optioncustJPanel
     */


    public optioncustJPanel(JPanel UserProcessContainer, FlightSchedule flightSch) {
        initComponents();
        this.flightSch = flightSch;
        this.st = st;
        this.UserProcessContainer = UserProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBestFlightjButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchBestFlightjButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        searchBestFlightjButton.setText("Search for best available flight");
        searchBestFlightjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBestFlightjButtonActionPerformed(evt);
            }
        });
        add(searchBestFlightjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 161, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Book Tickets");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 256, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 287, 47));
    }// </editor-fold>//GEN-END:initComponents

    private void searchBestFlightjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBestFlightjButtonActionPerformed
        // TODO add your handling code here:
       searchCustJPanel createJPanel = new searchCustJPanel(UserProcessContainer, flightSch);
       UserProcessContainer.add("searchCustJPanel", createJPanel);
       CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
       layout.next(UserProcessContainer);
    }//GEN-LAST:event_searchBestFlightjButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       bookTicketJPanel createJPanel = new bookTicketJPanel(UserProcessContainer, flightSch);
       UserProcessContainer.add("bookTicketJPanel", createJPanel);
       CardLayout layout = (CardLayout) UserProcessContainer.getLayout();
       layout.next(UserProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchBestFlightjButton;
    // End of variables declaration//GEN-END:variables
}
