/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Business.AccountInformation;
import Business.Address;
import Business.Demographic;
import Business.Driverlicense;
import Business.MedicalRecord;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import java.awt.Image;


/**
 *
 * @author owner
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Demographic demographic;

    public CreateJPanel(Demographic demographic) {
        initComponents();
        this.demographic = demographic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savingcheckingbuttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        PhoneNumberTextField = new javax.swing.JTextField();
        DobTextField = new javax.swing.JTextField();
        AgeTextField = new javax.swing.JTextField();
        HeightTextField = new javax.swing.JTextField();
        WeightTextField = new javax.swing.JTextField();
        SsnTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        StreetAddressTextField = new javax.swing.JTextField();
        CityTextField = new javax.swing.JTextField();
        StateTextField = new javax.swing.JTextField();
        ZipCodeTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        BankNameTextField = new javax.swing.JTextField();
        RoutingNoTextField = new javax.swing.JTextField();
        AccountNoTextField = new javax.swing.JTextField();
        AccountBalanceTextField = new javax.swing.JTextField();
        SavingsRadioBtn = new javax.swing.JRadioButton();
        CheckingRadioBtn = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        LicenseNoTextField = new javax.swing.JTextField();
        DOITextField = new javax.swing.JTextField();
        DOETextField = new javax.swing.JTextField();
        BloodTypeTextField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        MedicalRecordNoTextField = new javax.swing.JTextField();
        Alergy1TextField = new javax.swing.JTextField();
        Alergy2TextField = new javax.swing.JTextField();
        Alergy3TextField = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        AccountTypeTextField = new javax.swing.JTextField();
        ImageBtn = new javax.swing.JButton();
        ImageTextField = new javax.swing.JTextField();
        ImageJLabel = new javax.swing.JLabel();
        ClearBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Please Enter Your Details Below");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 350, 31));

        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 74, -1, -1));

        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 118, -1, -1));

        jLabel4.setText("Phone Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 153, -1, -1));

        jLabel5.setText("Date of birth:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 188, -1, -1));

        jLabel6.setText("Age:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 230, -1, -1));

        jLabel7.setText("Height:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 266, -1, -1));

        jLabel8.setText("Weight:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 303, -1, -1));

        jLabel9.setText("Social Security Number:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 338, -1, -1));
        add(FirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 71, 172, -1));
        add(LastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 115, 172, -1));
        add(PhoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 150, 172, -1));
        add(DobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 185, 172, -1));
        add(AgeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 227, 172, -1));
        add(HeightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 262, 172, -1));

        WeightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightTextFieldActionPerformed(evt);
            }
        });
        add(WeightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 300, 172, -1));
        add(SsnTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 335, 171, -1));

        jLabel12.setText("Street Address:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 427, -1, -1));

        jLabel13.setText("City:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 459, -1, -1));

        jLabel14.setText("State:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 494, -1, -1));

        jLabel15.setText("Zip Code:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 529, -1, -1));
        add(StreetAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 421, 192, -1));
        add(CityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 456, 192, -1));
        add(StateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 491, 192, -1));

        ZipCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipCodeTextFieldActionPerformed(evt);
            }
        });
        add(ZipCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 526, 192, -1));

        jLabel17.setText("Bank Name:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        jLabel18.setText("Bank Routing Number:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 682, -1, -1));

        jLabel19.setText("Account Number:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 717, -1, -1));

        jLabel20.setText("Account Balance:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 752, -1, -1));

        jLabel21.setText("Account Type:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 787, -1, -1));
        add(BankNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 170, -1));
        add(RoutingNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 675, 170, 30));
        add(AccountNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 714, 170, -1));
        add(AccountBalanceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 750, 170, -1));

        SavingsRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        savingcheckingbuttonGroup.add(SavingsRadioBtn);
        SavingsRadioBtn.setText("Savings");
        SavingsRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingsRadioBtnActionPerformed(evt);
            }
        });
        add(SavingsRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 783, -1, -1));

        CheckingRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        savingcheckingbuttonGroup.add(CheckingRadioBtn);
        CheckingRadioBtn.setText("Checking");
        CheckingRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckingRadioBtnActionPerformed(evt);
            }
        });
        add(CheckingRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 783, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 379, 960, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 960, 10));

        jLabel22.setText("License Number:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, -1, 20));

        jLabel24.setText("Date of Issue:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, -1, -1));

        jLabel25.setText("Date of Expiration:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 717, -1, -1));

        jLabel26.setText("Blood Type:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 752, -1, -1));

        LicenseNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicenseNoTextFieldActionPerformed(evt);
            }
        });
        add(LicenseNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 190, -1));
        add(DOITextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 680, 190, -1));
        add(DOETextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 714, 190, -1));
        add(BloodTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 749, 190, -1));

        jLabel28.setText("Medical Record Number:");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 427, -1, -1));

        jLabel29.setText("Alergy One:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 459, -1, -1));

        jLabel30.setText("Alergy Two:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 494, -1, -1));

        jLabel31.setText("Alergy Three:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 529, -1, -1));
        add(MedicalRecordNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 150, -1));
        add(Alergy1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 150, -1));
        add(Alergy2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 150, -1));
        add(Alergy3TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 150, -1));

        SubmitBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 830, 125, 46));
        add(AccountTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 784, 165, -1));

        ImageBtn.setText("Attach Image");
        ImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageBtnActionPerformed(evt);
            }
        });
        add(ImageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 181, 28));

        ImageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageTextFieldActionPerformed(evt);
            }
        });
        add(ImageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 164, -1));

        ImageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(ImageJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 280, 160));
        ImageJLabel.getAccessibleContext().setAccessibleName("ImageJLabel");

        ClearBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        add(ClearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 830, 125, 46));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile.jpg"))); // NOI18N
        jLabel10.setText("Demographic Information:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/address.png"))); // NOI18N
        jLabel11.setText("Address:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Medical.jpg"))); // NOI18N
        jLabel27.setText("Medical Record Information:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 300, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Account.png"))); // NOI18N
        jLabel16.setText("Account Information:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/License.jpg"))); // NOI18N
        jLabel23.setText("Driver's License Information:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void WeightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightTextFieldActionPerformed

    private void ZipCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipCodeTextFieldActionPerformed

    private void LicenseNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicenseNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicenseNoTextFieldActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:

//Demographic values
        demographic.setFirstName(FirstNameTextField.getText());
        demographic.setLastName(LastNameTextField.getText());
       // int phoneno = Integer.parseInt(PhoneNumberTextField.getText());
        demographic.setPhoneNumber(PhoneNumberTextField.getText());
        demographic.setDateOfBirth(DobTextField.getText());
        int age = Integer.parseInt(AgeTextField.getText());
        demographic.setAge(age);
        int weight = Integer.parseInt(WeightTextField.getText());
        demographic.setWeight(weight);
        int height = Integer.parseInt(HeightTextField.getText());
        demographic.setHeight(height);
        //int ssn = Integer.parseInt(SsnTextField.getText());
        demographic.setSsn(SsnTextField.getText());
//Address values
        Address address = new Address();
        address.setStreetAddress(StreetAddressTextField.getText());
        address.setCity(CityTextField.getText());
        address.setState(StateTextField.getText());
        int zip = Integer.parseInt(ZipCodeTextField.getText());
        address.setZipCode(zip);
        demographic.setAddress(address);
//Driver License Values
        Driverlicense driverLicense = new Driverlicense();
        driverLicense.setBloodType(BloodTypeTextField.getText());
        int licenseno = Integer.parseInt(LicenseNoTextField.getText());
        driverLicense.setLicenseNo(licenseno);
        driverLicense.setDateOfIssue(DOITextField.getText());
        driverLicense.setDateOfExpiration(DOETextField.getText());
        demographic.setDriverLicense(driverLicense);
//Medical Record Values
        MedicalRecord medicalRecord = new MedicalRecord();
        int medicalrecordno = Integer.parseInt(MedicalRecordNoTextField.getText());
        medicalRecord.setMedicalRecordNo(medicalrecordno);
        medicalRecord.setAlergy1(Alergy1TextField.getText());
        medicalRecord.setAlergy2(Alergy2TextField.getText());
        medicalRecord.setAlergy3(Alergy3TextField.getText());
        demographic.setMedicalRecord(medicalRecord);
//Account Information Values
        AccountInformation accountInformation = new AccountInformation();
        accountInformation.setBankName(BankNameTextField.getText());
        int routingno = Integer.parseInt(RoutingNoTextField.getText());
        accountInformation.setRoutingNo(routingno);
        int accountno = Integer.parseInt(AccountNoTextField.getText());
        accountInformation.setAccountNo(accountno);
        int accountbalance = Integer.parseInt(AccountBalanceTextField.getText());
        accountInformation.setAccountBalance(accountbalance);

        if (SavingsRadioBtn.isSelected()) {
            AccountTypeTextField.setText(SavingsRadioBtn.getText());
        } else if (CheckingRadioBtn.isSelected()) {
            AccountTypeTextField.setText(CheckingRadioBtn.getText());
        } else {
            AccountTypeTextField.setText(null);
        }
        accountInformation.setAccountType(AccountTypeTextField.getText());
        demographic.setAccountInformation(accountInformation);
        JOptionPane.showMessageDialog(null, "User created Successfully..!!");

    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void SavingsRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingsRadioBtnActionPerformed
        // TODO add your handling code here:
        AccountTypeTextField.setText(SavingsRadioBtn.getText());

    }//GEN-LAST:event_SavingsRadioBtnActionPerformed

    private void ImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageBtnActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Please attach your most recent photo. Accepted formats .jpg,.png, .jpeg");
        //JFileChooser chooser = new JFileChooser();
        //chooser.showOpenDialog(null);
        //File f = chooser.getSelectedFile();
          //ImageJLabel.setBounds(10, 10, 150, 150);
        //String filename = f.getAbsolutePath();
        //ImageTextField.setText(filename);
        //ImageIcon icon = new ImageIcon();
        //ImageJLabel.setIcon(icon);
        ///demographic.setPathName(filename);
        //OptionPane.showMessageDialog(null, "Image added Successfully..!!");

        JOptionPane.showMessageDialog(null, "Please attach your most recent photo. Accepted formats .jpg,.png, .jpeg");
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        ImageTextField.setText(filename);
        ImageIcon icon = new ImageIcon(filename);
        ImageJLabel.setIcon(icon);
        demographic.setpathName(filename);
        JOptionPane.showMessageDialog(null, "Image added Successfully..!!");

    }//GEN-LAST:event_ImageBtnActionPerformed

    private void CheckingRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckingRadioBtnActionPerformed
        // TODO add your handling code here:
        AccountTypeTextField.setText(CheckingRadioBtn.getText());

    }//GEN-LAST:event_CheckingRadioBtnActionPerformed

    private void ImageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImageTextFieldActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
        FirstNameTextField.setText("");
        LastNameTextField.setText("");
        PhoneNumberTextField.setText("");
        DobTextField.setText("");
        AgeTextField.setText("");
        WeightTextField.setText("");
        SsnTextField.setText("");
        HeightTextField.setText("");

//Address values
        StreetAddressTextField.setText("");
        CityTextField.setText("");
        StateTextField.setText("");
        ZipCodeTextField.setText("");

//Driver License Values
        BloodTypeTextField.setText("");
        LicenseNoTextField.setText("");
        DOITextField.setText("");
        DOETextField.setText("");
        ImageJLabel.setIcon(null);
        ImageTextField.setText("");

//Medical Record Values
        MedicalRecordNoTextField.setText("");
        Alergy1TextField.setText("");
        Alergy2TextField.setText("");
        Alergy3TextField.setText("");

//Account Information Values
        BankNameTextField.setText("");
        RoutingNoTextField.setText("");
        AccountNoTextField.setText("");
        AccountBalanceTextField.setText("");

        AccountTypeTextField.setText("");
        savingcheckingbuttonGroup.clearSelection();
        JOptionPane.showMessageDialog(null, "Details cleared Successfully..!!");


    }//GEN-LAST:event_ClearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountBalanceTextField;
    private javax.swing.JTextField AccountNoTextField;
    private javax.swing.JTextField AccountTypeTextField;
    private javax.swing.JTextField AgeTextField;
    private javax.swing.JTextField Alergy1TextField;
    private javax.swing.JTextField Alergy2TextField;
    private javax.swing.JTextField Alergy3TextField;
    private javax.swing.JTextField BankNameTextField;
    private javax.swing.JTextField BloodTypeTextField;
    private javax.swing.JRadioButton CheckingRadioBtn;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JTextField DOETextField;
    private javax.swing.JTextField DOITextField;
    private javax.swing.JTextField DobTextField;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField HeightTextField;
    private javax.swing.JButton ImageBtn;
    private javax.swing.JLabel ImageJLabel;
    private javax.swing.JTextField ImageTextField;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField LicenseNoTextField;
    private javax.swing.JTextField MedicalRecordNoTextField;
    private javax.swing.JTextField PhoneNumberTextField;
    private javax.swing.JTextField RoutingNoTextField;
    private javax.swing.JRadioButton SavingsRadioBtn;
    private javax.swing.JTextField SsnTextField;
    private javax.swing.JTextField StateTextField;
    private javax.swing.JTextField StreetAddressTextField;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField WeightTextField;
    private javax.swing.JTextField ZipCodeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup savingcheckingbuttonGroup;
    // End of variables declaration//GEN-END:variables
}
